kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1

steps:
  - name: build
    image: node:16.5.0
    pull: if-not-exists
    commands:
      - yarn
      - yarn build

  - name: publish
    image: plugins/gh-pages
    pull: if-not-exists
    environment:
      DRONE_REMOTE_URL: git@github.com:shinobi9/game-tools.git
    settings:
      pages_directory: build
      ssh_key:
        from_secret: SSH_KEY
