kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: build
    image: node:16.5.0
    pull: if-not-exists
    commands:
      - yarn config set registry https://registry.npm.taobao.org -g
      - yarn
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
    - name: cache
      path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    when:
      status:
        - failure
        - success

  - name: publish
    image: appleboy/drone-git-push
    pull: if-not-exists
    settings:
      remote: git@github.com:shinobi9/game-tools.git
      path: ./build/
      branch: gh-pages
      local_ref: gh-pages
      force: true
      ssh_key:
        from_secret: GAMETOOLS_DEPLOY_KEY



volumes:
  - name: cache
    host: 
      path: /tmp/cache