kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: build
    image: node:16.5.0
    pull: if-not-exists
    commands:
      - yarn config set registry https://registry.npm.taobao.org -g
      - yarn
      - yarn build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
    - name: cache
      path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    when:
      status:
        - failure
        - success

  - name: publish
    image: plugins/gh-pages
    pull: if-not-exists
    settings:
      target_branch: gh-pages
      pages_directory: public/
      remote_url: git@github.com:shinobi9/game-tools.git
      upstream_name: origin
      temporary_base: .tmp
      ssh_key:
        from_secret: GAMETOOLS_DEPLOY_KEY



volumes:
  - name: cache
    host: 
      path: /tmp/cache