kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push

  - name: build
    image: node:16.5.0
    pull: if-not-exists
    commands:
      - yarn
      - yarn build

  - name: publish
    image: plugins/gh-pages
    pull: if-not-exists
    settings:
      pages_directory: dist
      ssh_key:
        from_secret: SSH_KEY